# The base URL for the site.
baseURL = 'https://madisodr.github.io/'
# The title of the site.
title = 'Chirpy'
# Enable Git info › https://gohugo.io/methods/page/gitinfo/
enableGitInfo = false
# The default content language.
defaultContentLanguage = "en"
# Whether the default content language is in a subdirectory.
defaultContentLanguageInSubdir = false
# Whether the site has CJK language (Chinese, Japanese, Korean).
hasCJKLanguage = true

# Pagination settings.
[pagination]
  pagerSize = 5

# Make sure to include JSON output to support the search functionality.
[outputs]
  home = ["HTML", "RSS", "JSON"]

# Import the theme.
[module]
  [[module.imports]]
    path = "github.com/geekifan/hugo-theme-chirpy"

[security]
  allowContent = ['! ^text/html$']
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^node$', '^postcss$', '^tailwindcss$']
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG|SYSTEMDRIVE|PROGRAMDATA)$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']
  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['(?i)^https?://[a-z0-9]', '! ^https?://\d+\.', '! (?i)localhost', '! (?i)^https?://[^/?#]*@']
  [security.node]
    [security.node.permissions]
      allowAddons = ['tailwindcss']
      allowChildProcess = ['tailwindcss']
      allowRead = ['.']
      allowWorker = ['tailwindcss']
      allowWrite = []
      disable = false